/**
 * Regenerates src/dev/figmaRefs.generated.ts from the PNGs in assets/figma/.
 *
 * The renders come from the Figma MCP `get_screenshot` tool, saved as `<node-id>.png` with the
 * colon replaced by a dash (1:2189 → 1-2189.png). A node with an outer effect renders larger
 * than its frame — Home's drop shadow makes it 640×1478 for a 520×1358 frame — so the overlay
 * needs both boxes to line the frame up with the screen.
 *
 *   node scripts/figma-refs.cjs
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ASSETS = path.join(ROOT, 'assets', 'figma');
const OUT = path.join(ROOT, 'src', 'dev', 'figmaRefs.generated.ts');

/**
 * Frame boxes from get_metadata, and the node's render box from get_screenshot's
 * `original_width`/`original_height`. They differ only when the node has an outer effect:
 * Home's drop shadow renders 640×1478 around its 520×1358 frame. Both are in artboard units;
 * the PNG on disk is the same box scaled down, and is only checked for aspect here.
 */
const FRAMES = {
  '1:2': { name: 'DESIGN 2 — Home', height: 1358, render: [640, 1478] },
  '1:263': { name: 'JOBS 01 — Discover', height: 1440, render: [520, 1440] },
  '1:397': { name: 'JOBS 02 — Saved', height: 1440, render: [520, 1440] },
  '1:512': { name: 'JOBS 03 — Applied', height: 1440, render: [520, 1440] },
  '1:626': { name: 'JOBS 04 — Filters', height: 1440, render: [520, 1440] },
  '1:830': { name: 'JOBS 05 — Job Detail', height: 1720, render: [520, 1720] },
  '1:932': { name: 'JOBS 06 — Discover empty', height: 1440, render: [520, 1440] },
  '1:977': { name: 'JOBS 07 — Saved empty', height: 1440, render: [520, 1440] },
  '1:1010': { name: 'JOBS 08 — Applied empty', height: 1440, render: [520, 1440] },
  '1:1044': { name: 'CREATE 01 — + sheet', height: 1440, render: [520, 1440] },
  '1:1208': { name: 'CREATE 02 — New Resume', height: 1440, render: [520, 1440] },
  '1:1366': { name: 'RESUMES 01 — Grid', height: 1440, render: [520, 1440] },
  '1:1588': { name: 'RESUMES 02 — List', height: 1440, render: [520, 1440] },
  '1:1798': { name: 'RESUMES 03 — Card menu', height: 1440, render: [520, 1440] },
  '1:2061': { name: 'RESUMES 05 — First run', height: 1440, render: [520, 1440] },
  '1:2109': { name: 'RESUMES 04 — Score panel', height: 1520, render: [520, 1520] },
  '1:2189': { name: 'PROFILE 01 — Overview', height: 1440, render: [520, 1440] },
  '1:2313': { name: 'PROFILE 02 — Settings', height: 1440, render: [520, 1440] },
  '1:2402': { name: 'NOTIF 01 — Feed', height: 1440, render: [520, 1440] },
  '1:2498': { name: 'NOTIF 02 — Swipe actions', height: 1440, render: [520, 1440] },
  '1:2601': { name: 'NOTIF 03 — Row menu', height: 1440, render: [520, 1440] },
  '1:2711': { name: 'NOTIF 04 — Preferences', height: 1440, render: [520, 1440] },
  '1:2766': { name: 'NOTIF 05 — All caught up', height: 1440, render: [520, 1440] },
  '1:2788': { name: 'NOTIF 06 — First use', height: 1440, render: [520, 1440] },
  '1:2822': { name: 'NOTIF 07 — Push primer', height: 1720, render: [520, 1720] },
};

/** PNG stores width/height as big-endian uint32 at bytes 16 and 20 of the IHDR chunk. */
function pngSize(file) {
  const head = Buffer.alloc(24);
  const fd = fs.openSync(file, 'r');
  fs.readSync(fd, head, 0, 24, 0);
  fs.closeSync(fd);
  if (head.toString('ascii', 1, 4) !== 'PNG') throw new Error(`not a PNG: ${file}`);
  return { width: head.readUInt32BE(16), height: head.readUInt32BE(20) };
}

const entries = Object.entries(FRAMES).map(([id, frame]) => {
  const file = path.join(ASSETS, `${id.replace(':', '-')}.png`);
  if (!fs.existsSync(file)) throw new Error(`missing render for ${id} (${file})`);

  // The PNG is the render box scaled down, so its aspect must still match. A mismatch means the
  // file was re-exported at different bounds and the overlay would sit off by that much.
  const png = pngSize(file);
  const [renderWidth, renderHeight] = frame.render;
  const drift = Math.abs(png.width / png.height - renderWidth / renderHeight);
  if (drift > 0.005) {
    throw new Error(
      `${id}: PNG is ${png.width}x${png.height} but the render box is ${renderWidth}x${renderHeight}`,
    );
  }

  return { id, name: frame.name, height: frame.height, render: { width: renderWidth, height: renderHeight } };
});

const lines = [
  '// Generated by scripts/figma-refs.cjs — do not edit by hand.',
  "import type { FigmaRef } from './figmaRefs';",
  '',
  'export const FIGMA_REFS: readonly FigmaRef[] = [',
  ...entries.map(
    (e) =>
      `  {\n` +
      `    id: '${e.id}',\n` +
      `    name: '${e.name.replace(/'/g, "\\'")}',\n` +
      `    frameHeight: ${e.height},\n` +
      `    renderWidth: ${e.render.width},\n` +
      `    renderHeight: ${e.render.height},\n` +
      `    source: require('../../assets/figma/${e.id.replace(':', '-')}.png'),\n` +
      `  },`,
  ),
  '];',
  '',
];

fs.writeFileSync(OUT, lines.join('\n'));
console.log(`wrote ${entries.length} refs to ${path.relative(ROOT, OUT)}`);
